# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

r_packages:
  - covr

after_success:
  - |
    Rscript \
      --default-packages='datasets,utils,grDevices,graphics,stats,methods' \
      -e 'covr::codecov(line_exclusions = c("inst/include/testthat/testthat.h", "inst/include/testthat/vendor/catch.h"))'
